package com.ftn.dr_help.selenium;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestOne {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;

@Before
public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
	 driver = new ChromeDriver();
	 js = (JavascriptExecutor) driver;
	 vars = new HashMap<String, Object>();
}

@After
public void tearDown() {
	driver.quit();
}

@Test
public void testOne() {
	 driver.get("http://localhost:3000/login");
	 driver.manage().window().setSize(new Dimension(1042, 554));
	 driver.findElement(By.id("tb_email")).click();
	 driver.findElement(By.id("tb_email")).sendKeys("admin@admin");
	 driver.findElement(By.id("tb_password")).click();
	 driver.findElement(By.id("tb_password")).sendKeys("1234");
	 driver.findElement(By.cssSelector(".btn")).click();
	 
	 (new WebDriverWait(driver, 10)).until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Requests")));
	 
	 driver.findElement(By.linkText("Requests")).click();
	 driver.findElement(By.linkText("Appointments")).click();
	 driver.findElement(By.cssSelector(".row")).click();
}
}

